services:
  mqtt-broker:
    build:
      context: .
      dockerfile: docker/Dockerfile.mqtt
    image: mqtt/mosquitto
    container_name: iot-collector-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt-app

networks:
  mqtt-app:
    external: false
    driver: bridge
    name: mqtt-app
