services:
  mqtt-broker:
    build:
      context: .
      dockerfile: docker/Dockerfile.mqtt
    image: mqtt/mosquitto
    container_name: iot-collector-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt-app
  mongo:
    ports:
      - '27017:27017'
    container_name: iot-collector-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=forzajuve
    image: mongo
networks:
  mqtt-app:
    external: false
    driver: bridge
    name: mqtt-app
